[[!template id=note text="""
Other posts in the *Installing Kolab series*:
 - **[part 1](/posts/kolab_fail/ "Database error after setup script")**
 - **[part 3](/posts/kolab_fail-3/ "SMTP Error 454")**
 - **[part 4](/posts/kolab_fail-4/ "Setup script failure on 3.1")**
 - **[part 5](/posts/kolab_up/ "Kolab, Up and Running on   CentOS 6")**
"""]]

I’ve been told not to run setup-kolab twice, and to try the
development packages provided by
<http://mirror.kolabsys.com/pub/debian/kolab-3.0/>.
Unfortunately, setup-kolab failed, again.
    
    Traceback (most recent call last):
      File "/usr/sbin/setup-kolab", line 42, in <module>
        setup.run()
      File "/usr/lib/python2.7/dist-packages/pykolab/setup/__init__.py", line 43, in run
        components.execute('_'.join(to_execute))
      File "/usr/lib/python2.7/dist-packages/pykolab/setup/components.py", line 170, in execute
        execute(component)
      File "/usr/lib/python2.7/dist-packages/pykolab/setup/components.py", line 202, in execute
        components[component_name]['function'](conf.cli_args, kw)
      File "/usr/lib/python2.7/dist-packages/pykolab/setup/setup_ldap.py", line 247, in execute
        setup_ds_admin,
    UnboundLocalError: local variable 'setup_ds_admin' referenced before assignment

At this point, I don’t really know what do do any more!
I guess I’ll have to find out how to report a bug in the kolab
community. Let’s this how this goes…

[[!tag Kolab freeSoftware bug lang:en]][[!meta language="en"]]]]
[[!meta title="Installing kolab, part 2"]]
